stages:
  - lint
  - test
  - build
  - deploy

variables:
  RAILS_ENV: test

lint_backend:
  stage: lint
  script:
    - gem install rubocop
    - rubocop
  artifacts:
    paths:
      - backend_lint_report.html
    expire_in: 1 month
  rules:
    - if: '$CI_COMMIT_BRANCH'

lint_frontend:
  stage: lint
  script:
    - npm install
    - npm run lint
  artifacts:
    paths:
      - frontend_lint_report.html
    expire_in: 1 month
  rules:
    - if: '$CI_COMMIT_BRANCH'

test_backend:
  stage: test
  script:
    - bundle install
    - bundle exec rake db:create RAILS_ENV=test
    - bundle exec rake db:migrate RAILS_ENV=test
    - bundle exec rails test
  artifacts:
    paths:
      - test_report.xml
    expire_in: 1 month
  rules:
    - if: '$CI_COMMIT_BRANCH'

test_frontend:
  stage: test
  script:
    - npm install
    - npm test
  artifacts:
    paths:
      - frontend_test_report.html
    expire_in: 1 month
  rules:
    - if: '$CI_COMMIT_BRANCH'

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  rules:
    - if: '$CI_COMMIT_BRANCH'