stages:
  - lint
  - test

lint-frontend:
  stage: lint
  before_script:
    - npm install
    - npm i -D eslint
  script:
    - cd frontend/
    - mkdir -p frontend-lint-report
    - touch ./frontend-lint-report/lint-report.txt
    - npm run lint > ./frontend-lint-report/lint-report.txt
  artifacts:
    paths:
      - frontend/frontend-lint-report/lint-report.txt
    expire_in: 1 month
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "main"

lint-backend:
  stage: lint
  before_script:
    - gem install rubocop
  script:
    - cd backend/
    - bundle install
    - mkdir -p backend-lint-report
    - touch ./backend-lint-report/lint-report.txt
    - rubocop --format txt --out ./backend-lint-report/lint-report.txt
  artifacts:
      path:
        - backend/backend-lint-report/lint-report.txt
      expire_in: 1 month
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "main"


unit-tests:
  stage: test
  script:
    - cd backend/
    - ./bin/rails test
  artifacts:
      path:
        - backend/test/controllers/contacts_controller_test.rb
      expire_in: 1 month
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "main"